// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storydb

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

func New(db DBTX) *Queries1 {
	return &Queries1{db: db}
}

type Queries1 struct {
	db DBTX
}

func (q *Queries1) Close() {
	panic("unimplemented")
}

func (q *Queries1) WithTx(tx pgx.Tx) *Queries1 {
	return &Queries1{
		db: tx,
	}
}
