// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Story struct {
	StoryID        int32
	Originalstory  string
	Pulledrequests pgtype.Int4
	Updatedstory   string
	AuthorID       pgtype.Int4
}
