// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storydb

import (
)

type Story struct {
	StoryID        int
	Originalstory  string
	Pulledrequests int
	Updatedstory   string
	AuthorID       int
}
