name: ci-test

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Nikhil@123k
          POSTGRES_DB: project3postgresql1
        ports:
          - 5432:5432

    steps: 
    - name: Set up Go 1.x
      uses: actions/setup-go@v2 
      with:
        go-version: ^1.23.4
      id: go 

    - name: Check out code into the Go directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz -o migrate.tar.gz
        tar -xvzf migrate.tar.gz
        sudo mv migrate /usr/local/bin/migrate
        sudo chmod +x /usr/local/bin/migrate
        which migrate
        migrate -version

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
